# Generated by Django 5.2 on 2025-05-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sid', models.CharField(db_index=True, max_length=255, unique=True)),
                ('account_sid', models.CharField(db_index=True, max_length=255)),
                ('from_number', models.CharField(max_length=50)),
                ('to_number', models.CharField(max_length=50)),
                ('body', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
