# Generated by Django 5.2 on 2025-05-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_webhook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliomessage',
            name='profile_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
